
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const Copyright = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50">
      <Header />
      
      <div className="pt-24 pb-12 px-4">
        <div className="max-w-4xl mx-auto">
          <div className="bg-white rounded-lg p-8 shadow-lg">
            <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent mb-8">
              Copyright Notice
            </h1>
            
            <div className="prose prose-lg max-w-none text-gray-700">
              <p className="text-sm text-gray-500 mb-8">Last updated: {new Date().toLocaleDateString()}</p>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Copyright Ownership</h2>
                <p>
                  All content, design, graphics, interfaces, code, and software on StuBud AI ("the Website") 
                  are the exclusive property of StuBud AI and are protected by copyright, trademark, and other 
                  intellectual property laws. © 2024 StuBud AI. All rights reserved.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Protected Content</h2>
                <p className="mb-4">
                  The following elements are protected by copyright:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Website design, layout, and visual elements</li>
                  <li>Source code, algorithms, and software components</li>
                  <li>Text content, descriptions, and documentation</li>
                  <li>Graphics, logos, and visual branding</li>
                  <li>User interface and user experience design</li>
                  <li>Educational content and study materials</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">AI-Generated Content</h2>
                <p className="mb-4">
                  Regarding content generated by our AI system:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>AI-generated answers are created using Google's Gemini API</li>
                  <li>Users receive generated content for educational use only</li>
                  <li>Generated content should be treated as reference material</li>
                  <li>Users do not gain copyright ownership of AI-generated content</li>
                  <li>Commercial use of generated content requires explicit permission</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Permitted Uses</h2>
                <p className="mb-4">
                  You may use StuBud AI content under the following conditions:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Personal educational purposes and academic study</li>
                  <li>Non-commercial reference and learning activities</li>
                  <li>Fair use as defined by applicable copyright laws</li>
                  <li>Temporary downloading for offline study (where technically possible)</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Prohibited Uses</h2>
                <p className="mb-4">
                  The following uses are strictly prohibited:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Reproducing, distributing, or republishing website content</li>
                  <li>Creating derivative works based on our platform</li>
                  <li>Commercial exploitation of any content or features</li>
                  <li>Reverse engineering or copying source code</li>
                  <li>Using content for competing educational platforms</li>
                  <li>Mass downloading or scraping of generated content</li>
                  <li>Removing or altering copyright notices</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Third-Party Content</h2>
                <p className="mb-4">
                  StuBud AI may contain content or links to third-party materials:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Third-party content remains the property of its respective owners</li>
                  <li>We do not claim ownership of user-submitted questions</li>
                  <li>Google Gemini API responses are subject to Google's terms</li>
                  <li>Educational references may be subject to separate copyrights</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Trademark Information</h2>
                <p>
                  "StuBud AI" and associated logos are trademarks of StuBud AI. All other trademarks, 
                  service marks, and trade names mentioned on this website are the property of their 
                  respective owners.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Digital Millennium Copyright Act (DMCA)</h2>
                <p className="mb-4">
                  We respect intellectual property rights and comply with the DMCA. If you believe 
                  your copyrighted work has been used inappropriately:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Contact us immediately with detailed information</li>
                  <li>Provide proof of copyright ownership</li>
                  <li>Include your contact information</li>
                  <li>Specify the allegedly infringing content</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">License for Educational Use</h2>
                <p>
                  We grant students a limited, non-exclusive, non-transferable license to use 
                  AI-generated content for personal educational purposes, subject to these terms 
                  and our Terms of Service.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Copyright Infringement</h2>
                <p className="mb-4">
                  Users agree not to:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Submit copyrighted material without permission</li>
                  <li>Use the service to generate content that infringes copyrights</li>
                  <li>Distribute copyrighted educational materials without authorization</li>
                  <li>Claim ownership of AI-generated content</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Enforcement</h2>
                <p>
                  We actively protect our intellectual property rights and will pursue legal action 
                  against unauthorized use, reproduction, or distribution of our copyrighted materials.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">Copyright Contact Information</h2>
                <p>
                  For copyright-related inquiries, permissions, or DMCA notices, contact:
                </p>
                <ul className="list-none mt-4 space-y-1">
                  <li><strong>Email:</strong> copyright@stubudai.com</li>
                  <li><strong>Subject Line:</strong> Copyright Inquiry - StuBud AI</li>
                  <li><strong>Response Time:</strong> Within 5 business days</li>
                </ul>
                <p className="mt-4 text-sm text-gray-600">
                  Please include all relevant documentation and contact information in your inquiry.
                </p>
              </section>
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default Copyright;
